# Generated by Django 4.0.2 on 2022-03-03 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0004_alter_user_info_reg_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 32, 10, 96356), null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_kind', models.CharField(max_length=10)),
                ('board_no', models.IntegerField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=1000)),
                ('b_content', models.TextField()),
                ('b_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 32, 10, 96356))),
                ('b_count', models.IntegerField(default=1)),
                ('pw_for_one_request', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.user_info')),
            ],
        ),
    ]
