# Generated by Django 4.0.2 on 2022-03-03 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 32, 47, 636267)),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 32, 47, 636267), null=True),
        ),
    ]
