# Generated by Django 4.0.2 on 2022-03-03 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0002_alter_board_b_date_alter_board_board_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 34, 27, 494755)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 34, 27, 495773), null=True),
        ),
    ]
