# Generated by Django 4.0.2 on 2022-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_content', models.TextField()),
                ('event_dt', models.DateTimeField()),
                ('event_st_dt', models.DateTimeField()),
                ('event_en_dt', models.DateTimeField()),
                ('event_cnt', models.IntegerField(default=1)),
            ],
        ),
    ]
