# Generated by Django 4.0.2 on 2022-03-03 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_regno', models.IntegerField()),
                ('user_phoneno', models.IntegerField()),
                ('user_zipcode', models.IntegerField()),
                ('user_add1', models.CharField(max_length=50)),
                ('user_add2', models.CharField(max_length=50)),
                ('reg_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 16, 27, 846451))),
            ],
        ),
    ]
