# Generated by Django 4.0.2 on 2022-03-07 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_no', models.CharField(max_length=8)),
                ('news_kind', models.CharField(max_length=10)),
                ('news_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 10, 4, 35, 417034))),
                ('news_content', models.TextField()),
                ('news_keyword', models.CharField(max_length=50)),
                ('weather_info', models.CharField(max_length=20)),
                ('news_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=50)),
                ('notice_content', models.TextField()),
                ('notice_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 10, 4, 35, 418034))),
                ('notice_cnt', models.IntegerField(default=1)),
                ('notice_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Related_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_no', models.CharField(max_length=8)),
                ('news_code_no', models.CharField(max_length=8)),
                ('news_info', models.CharField(max_length=50)),
                ('accident_info', models.CharField(max_length=50)),
            ],
        ),
    ]
