# Generated by Django 4.0.2 on 2022-03-07 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_info',
            name='news_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 8, 55, 43, 7210)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 8, 55, 43, 7210)),
        ),
    ]
