# Generated by Django 4.0.2 on 2022-03-03 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Info',
            fields=[
                ('news_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('news_kind', models.CharField(max_length=10)),
                ('news_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 16, 24, 43, 994948))),
                ('news_content', models.TextField()),
                ('news_keyword', models.CharField(max_length=50)),
                ('weather_info', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Related_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_no', models.CharField(max_length=8)),
                ('news_code_no', models.CharField(max_length=8)),
                ('news_info', models.CharField(max_length=50)),
                ('accident_info', models.CharField(max_length=50)),
            ],
        ),
    ]
