# Generated by Django 4.0.2 on 2022-03-03 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0005_alter_news_info_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=50)),
                ('notice_content', models.TextField()),
                ('notice_dt', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 17, 58, 3, 489158))),
                ('notice_cnt', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='news_info',
            name='news_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 3, 17, 58, 3, 489158)),
        ),
    ]
